using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AccessCity.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522170000_AddWorkerJobAndMessageReliability")]
    public partial class AddWorkerJobAndMessageReliability : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS public.osm_import_jobs (
                    id uuid PRIMARY KEY,
                    status character varying(50) NOT NULL,
                    file_path character varying(2048) NOT NULL,
                    city_name character varying(150) NOT NULL,
                    queued_at_utc timestamp with time zone NOT NULL,
                    started_at_utc timestamp with time zone NULL,
                    finished_at_utc timestamp with time zone NULL,
                    attempts integer NOT NULL,
                    feed_ingestion_run_id bigint NULL,
                    error_summary text NULL,
                    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
                );

                CREATE TABLE IF NOT EXISTS public.processed_integration_messages (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    message_id character varying(100) NOT NULL,
                    topic character varying(250) NOT NULL,
                    consumer_group_id character varying(250) NOT NULL,
                    event_type character varying(250) NOT NULL,
                    processed_at_utc timestamp with time zone NOT NULL
                );

                CREATE INDEX IF NOT EXISTS "IX_osm_import_jobs_status_queued"
                    ON public.osm_import_jobs (status, queued_at_utc);

                CREATE INDEX IF NOT EXISTS "IX_processed_integration_messages_processed_at"
                    ON public.processed_integration_messages (processed_at_utc);

                CREATE UNIQUE INDEX IF NOT EXISTS "UX_processed_integration_messages_identity"
                    ON public.processed_integration_messages (message_id, consumer_group_id);

                CREATE INDEX IF NOT EXISTS "IX_hazard_report_reported_at_brin"
                    ON public.hazard_report USING BRIN (reported_at);

                CREATE INDEX IF NOT EXISTS "IX_feed_ingestion_runs_started_at_brin"
                    ON public.feed_ingestion_runs USING BRIN ("StartedAt");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "processed_integration_messages");
            migrationBuilder.DropTable(name: "osm_import_jobs");

            migrationBuilder.Sql(
                """
                DROP INDEX IF EXISTS public."IX_hazard_report_reported_at_brin";
                DROP INDEX IF EXISTS public."IX_feed_ingestion_runs_started_at_brin";
                """);
        }
    }
}
