apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: accesscity

resources:
  - ../kubernetes

replicas:
  - name: accesscity-api
    count: 10
  - name: accesscity-worker
    count: 30

patches:
  - path: api-deployment-patch.yaml
    target:
      kind: Deployment
      name: accesscity-api
  - path: worker-deployment-patch.yaml
    target:
      kind: Deployment
      name: accesscity-worker
  - path: api-config-capacity-patch.yaml
    target:
      kind: ConfigMap
      name: accesscity-api-config
  - path: worker-config-capacity-patch.yaml
    target:
      kind: ConfigMap
      name: accesscity-worker-config
  - path: keda-api-capacity-patch.yaml
    target:
      group: keda.sh
      version: v1alpha1
      kind: ScaledObject
      name: accesscity-api-scalability
  - path: keda-worker-capacity-patch.yaml
    target:
      group: keda.sh
      version: v1alpha1
      kind: ScaledObject
      name: accesscity-worker-kafka
