import MapScreen from '@/components/MapView/MapScreen';
import { StyleSheet } from 'react-native';

export default function MapPage() {
  return <MapScreen />;
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  searchContainer: { position: 'absolute', top: 60, left: 16, right: 80 },
  searchBox: {
    height: 56,
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  input: { flex: 1, paddingHorizontal: 10, fontSize: 16, color: '#111827' },
  filterButton: {
    position: 'absolute',
    top: 60,
    right: 16,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#1D4ED8',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
  },
  startRouteButton: {
    position: 'absolute',
    bottom: 40,
    left: 20,
    right: 20,
    backgroundColor: '#1D4ED8',
    borderRadius: 16,
    paddingVertical: 18,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 8,
  },
  startRouteButtonText: { color: '#FFF', fontSize: 18, fontWeight: '800' },
  routeCard: {
    position: 'absolute',
    bottom: 30,
    left: 16,
    right: 16,
    backgroundColor: '#1D4ED8',
    borderRadius: 20,
    padding: 20,
    elevation: 10,
  },
  routeTitle: { color: '#FFF', fontSize: 26, fontWeight: '900' },
  routeSubtitle: { color: '#DBEAFE', fontSize: 16, marginTop: 4 },
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  overlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.4)' },
  filterSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 24,
    minHeight: 400,
  },
  dragHandle: {
    width: 40,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#E5E7EB',
    alignSelf: 'center',
    marginBottom: 20,
  },
  filterTitle: { fontSize: 22, fontWeight: '900', color: '#111827', marginBottom: 20 },
  sheetDivider: { height: 1, backgroundColor: '#F3F4F6', marginBottom: 20 },
  filterCard: { backgroundColor: '#F9FAFB', borderRadius: 20, padding: 16, marginBottom: 24 },
  checkboxRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
  checkbox: { width: 26, height: 26, borderRadius: 8, borderWidth: 2, borderColor: '#D1D5DB', marginRight: 12, justifyContent: 'center', alignItems: 'center' },
  checkboxChecked: { backgroundColor: '#1D4ED8', borderColor: '#1D4ED8' },
  checkboxLabel: { fontSize: 17, color: '#374151', fontWeight: '500' },
  applyButton: { backgroundColor: '#111827', borderRadius: 16, paddingVertical: 16, alignItems: 'center' },
  applyButtonText: { color: '#FFF', fontSize: 16, fontWeight: '700' },
  hazardPreviewCard: {
    position: 'absolute',
    left: 20,
    top: 140,
    width: 240,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 15,
    elevation: 8,
  },
  hazardPreviewClose: { position: 'absolute', top: 12, right: 12, padding: 4 },
  hazardPreviewLabel: { fontSize: 12, color: '#D97706', fontWeight: '800', marginBottom: 4 },
  hazardPreviewTitle: { fontSize: 19, fontWeight: '900', color: '#111827', marginBottom: 12 },
  hazardPreviewDetailsButton: { backgroundColor: '#FFF7ED', borderRadius: 12, paddingVertical: 10, alignItems: 'center' },
  hazardPreviewDetailsText: { color: '#D97706', fontSize: 14, fontWeight: '700' },
});
